### ISSUE TITLE
Níl an focal 'libh' ag obair

### ISSUE THREAD

**Issue by ghost** [ConorSheehan1/beach-litriochta#1]
Tá na litír 
B I L E R H A
le fáil. Níl "libh" ag obair mar rogha.

An bhfuil an ceart agam no an bhfuil mé trína chéile?

GRMA. Is bréa liom an cluiche!

**Comment by ConorSheehan1** [comment]
Tá an ceart agat. Bainim úsáid as an liosta focail chéanna le foclach agus tá roinnt focail in easnamh. Táim ag smaoineamh ar liosta focail breise a chuir le chéile. Cuirfidh mé 'libh' ar cinnte!

Tá áthas orm go bhfuil tú ag baint sult as an gcluiche! Más féidir leat réalt a thabhairt dom anseo cabhróidh sé go mór liom

**Comment by ConorSheehan1** [comment]
Chuir mé issue nua le liosta focail breise anseo: #2
Má tá aon focal eile gur mhaith leat a bheith sa cluiche, cur comment ansin agus déanfaidh mé iarracht iad a chuir sa chluiche
